### ISSUE TITLE
SplashScreen scale 200 support

### ISSUE THREAD

**Issue by powerdude** [spadapet/universal-image-scaler#1]
Hi,

I just found your tool and it's a godsend.  Any chance of supporting 1240x600 image creation?

thanks

cliff

**Comment by spadapet** [comment]
That size should be supported now, make sure that your source image is at least 1240x600 for that option to be available.

**Comment by spadapet** [comment]
By the way, here's how I see 1240x600 in the UI. Notice that my source image is 2480x1200.

![image](https://cloud.githubusercontent.com/assets/2523431/21970654/5c6b4ff4-db5d-11e6-9778-2dc71c2606e7.png)

**Comment by spadapet** [comment]
I'll close this for now, but reopen and add comments if there is a problem with the current design.

**Comment by powerdude** [comment]
Thanks.  I'll look at it next weekend and let you know.  Thanks for implementing it.
