### ISSUE TITLE
VSIX Installer error when trying to install on VS Community 2017 RC.4 +26206.0

### ISSUE THREAD

**Issue by Dbquity** [spadapet/universal-image-scaler#2]
First, thanks for sharing this productivity booster!
Unfortunately, I have not been able to install it yet, because I run into this error:
![2017-03-01](https://cloud.githubusercontent.com/assets/25459675/23455175/fe3995c8-fe6e-11e6-8e2d-8ab12cd2818b.png)
I first reported it [here](https://developercommunity.visualstudio.com/content/problem/22460/cannot-install-the-uwp-visual-assets-generator-ver.html). As you can see, the VS team looked at it and concluded that the issue was in this tool itself, so I am opening this issue.

Best regards
Lars Hammer

**Comment by spadapet** [comment]
Thanks I'll try installing it into VS Community 2017 RC. I think I only tried it with the full blown Enterprise install.

**Comment by spadapet** [comment]
Aha, I didn't notice it before, but "UWP Visual Assets Generator" is not my extension :)
This is "Windows Universal App Image Scaler" which is a very similar thing.
Mine does install in VS 2017, which I just verified.

**Comment by Dbquity** [comment]
Thanks for being so forthcoming despite the mistanken address. I apologize for that!
Regards
/Lars
